# Generated by Django 5.0.2 on 2025-03-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
