import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoginModal from "./components/modals/LoginModal";
import Modal from "./components/modals/Modal";
import Navbar from "./components/navbar/Navbar";

const inter=Inter({subsets:["latin"]});

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content=(
    <p>Contenido - prueba</p>
  )
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Navbar/>
        <div className="pt-24 md:pt-28 lg:pt-32">
          {children}
        </div>
        <LoginModal/>
      </body>
    </html>
  );
}
